#â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„
#â–ˆâ–‘â–„â–„â–€â–ˆâ–‘â–„â–„â–ˆâ–‘â–„â–„â–‘â–ˆâ–‘â–ˆâ–ˆâ–‘â–ˆâ–ˆâ–„â–ˆâ–ˆâ–„â–‘â–„â–ˆâ–‘â–„â–„â–€â–ˆâ–‘â–„â–„â–ˆ
#â–ˆâ–‘â–€â–€â–‘â–ˆâ–‘â–„â–„â–ˆâ–‘â–€â–€â–‘â–ˆâ–‘â–ˆâ–ˆâ–‘â–ˆâ–ˆâ–‘â–„â–ˆâ–ˆâ–‘â–ˆâ–ˆâ–‘â–€â–€â–‘â–ˆâ–„â–„â–€â–ˆ
#â–ˆâ–‘â–ˆâ–ˆâ–‘â–ˆâ–„â–„â–„â–ˆâ–ˆâ–ˆâ–ˆâ–‘â–ˆâ–ˆâ–„â–„â–„â–ˆâ–„â–„â–„â–ˆâ–ˆâ–„â–ˆâ–ˆâ–„â–ˆâ–ˆâ–„â–ˆâ–„â–„â–„â–ˆ
#â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€
#
# Aequitas Anti-Cheat Â© , C. Marco 2024
# Config Version 1.0.0

messages:
  logo: "&c[&6ğ“ğ“®ğ“ºğ“¾ğ“²ğ“½ğ“ªğ“¼&c]&7:" # The logo used by this software in text messages.
  missing-permission: "{LOGO} &4You are missing permissions to run this!" # Printed when running command without necessary permissions.
  unknown-command: "{LOGO} &4This command syntax is unknown or wrong." # Printed when running unknown command syntax.